### ISSUE TITLE
doesn't detect this contract is a contract 

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/address-vision-port#16]
it would also be dope if it detected that this is a cohort stream

https://address.vision/0x2Be18e07C7be0a2CC408C9E02C90203B2052D7DE

but for some reason it doesn't even see it as a contract?

<img width="616" alt="image" src="https://github.com/BuidlGuidl/address-vision-port/assets/2653167/b20c347a-f621-49b1-ae7c-f1c76ba05ba6">

**Comment by portdeveloper** [comment]
Thanks! Looks like someone didn't test enough before deploying into production :D 

Fixed at https://github.com/BuidlGuidl/address-vision-port/commit/41bc69b7e0ce086b15e7c1b6261128f8c4ac70a0
