### ISSUE TITLE
Possible removal of the ENS/address in the card headers

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/address-vision-port#17]
Since we already have the ENS or address big in the top left, I think headers like this could be changed to just:

Ethereum - Polygon - Optimism etc... and the one in the links section can be removed.

Thoughts?

![image](https://github.com/BuidlGuidl/address-vision-port/assets/12072395/89a2ab86-2c27-4784-a1f7-fb570b6b3ece)

**Comment by portdeveloper** [comment]
Good idea! I think those make the page a little more crowded than it should be. Maybe we can deploy the change to another address and see how it works.
