### ISSUE TITLE
Add quick copy address button

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/address-vision-port#24]
Sometimes I type in an ENS looking to quickly get the address copied.  Would be nice to have the "copy address" button back in one place.  Maybe in the large ENS and balance card here?

![image](https://github.com/BuidlGuidl/address-vision-port/assets/12072395/dbe6382e-161c-4fe7-a9f8-576042377d68)

**Comment by portdeveloper** [comment]
This is a great little addition, let me do it!

**Comment by portdeveloper** [comment]
https://github.com/BuidlGuidl/address-vision-port/assets/108868128/740108e7-7020-4e92-9773-de65b632c694

How does this look? @ZakGriffith

**Comment by ZakGriffith** [comment]
Fixed in #27
