### ISSUE TITLE
Vertically center ENS name in top address component.

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/address-vision-port#26]
The ENS name does appear vertically centered (Even if it actually is).

![image](https://github.com/BuidlGuidl/address-vision-port/assets/12072395/efe4292c-6678-411f-8b46-863cc8d8f55d)

Nudge this ENS up just a bit so it looks all nice. (Very nitpicky, sorry!

**Comment by portdeveloper** [comment]
![image](https://github.com/BuidlGuidl/address-vision-port/assets/108868128/a88a6489-8d74-4f39-93c8-9450a445466f)
I tried to fix this with minimal changes but I think changing the addressinput component altogether is an option here too.

**Comment by ZakGriffith** [comment]
Fixed in #27
