### ISSUE TITLE
🌐 etherscan link 

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/address-vision-port#30]
i used to click the address to get to etherscan but I think that has changed so it links to address vision (which I think makes sense!) 

but now it's hard to get to etherscan for this address (maybe it's just because it's a safe): https://address.vision/dao.buidlguidl.eth

**Comment by portdeveloper** [comment]
Fixed at [https://github.com/BuidlGuidl/address-vision-port/commit/9c2ac0608750e75686c4c2b0e9518811dfb960e4](url)
