### ISSUE TITLE
filter out the prefix from addresses eth:0x

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/address-vision-port#34]
i wish address vision would filter out the prefix on these addresses automatically 

if I paste in eth:0x8cD78a945c6D209fe8C7ed8Ee1712F43bec17781 from a gnosis safe I have to go clean out the prefix, we might see this more and it would be nice if address vision could handle it gracefully :) :)

**Comment by portdeveloper** [comment]
Thanks! Already fixed! 🤝
