### ISSUE TITLE
Padding issues on iphone 13 resolution

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/address-vision-port#49]
The "get started" text needs some padding on an iphone 13 resolution.  

![image](https://github.com/BuidlGuidl/address-vision-port/assets/12072395/b5c64b97-70b5-454d-a117-ab4f293b847b)

**Comment by portdeveloper** [comment]
Fixed in #50 , I am aware that some other problems exist, will fix them soon while rewriting the addresscard!
