### ISSUE TITLE
logo standardization

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/address-vision-port#55]
### Is there an existing issue for this?

- [X] I have looked through the [existing issues](https://github.com/scaffold-eth/scaffold-eth-2/issues)

### Current Behavior

Currently we are using an emoji as a logo: 👀, but it renders differently on different operating systems. 
We should come up with a logo or think of something else.

**Comment by portdeveloper** [comment]
https://github.com/BuidlGuidl/address-vision-port/assets/108868128/1534b1d5-b33b-4284-8831-5b5348ecf065

Perhaps using a kaomoji could be cool? lmk what you think

**Comment by ceeriil** [comment]
How about using an SVG rather than text?

**Comment by portdeveloper** [comment]
I think emojis are copyrighted if you render it anywhere but the client @ceeriil

**Comment by portdeveloper** [comment]
was just looking around... 
I found this: https://github.com/microsoft/fluentui-emoji

which is amazing! The emojis have the MIT license!

**Comment by portdeveloper** [comment]
Finally closing, now everyone will see the same emoji in address.vision!
