### ISSUE TITLE
trim input

### ISSUE THREAD

**Issue by austintgriffith** [BuidlGuidl/address-vision-port#57]
I had an extra space on the end or start of an address and it went crazy 

could we just auto trim anything that gets pasted in somehow

**Comment by portdeveloper** [comment]
fixed at [link to commit](https://github.com/BuidlGuidl/address-vision-port/commit/9b309cb4502b74c74194a62240090d3d74935b87)

Sorry about this, I missed to add a simple .trim() when I was playing around with the logic!
