### ISSUE TITLE
Cursor focus after clicking X to remove address

### ISSUE THREAD

**Issue by ZakGriffith** [BuidlGuidl/address-vision-port#62]
It would be a helpful QOL update to focus the cursor in the address input after the "X" is clicked to remove an address.  (Disregard that first click on the X that did nothing, that was the recording software)

![clickGIF](https://github.com/BuidlGuidl/address-vision-port/assets/12072395/6fc1c0ed-7802-4dd1-ab09-38e9629008d5)

**Comment by portdeveloper** [comment]
done at https://github.com/BuidlGuidl/address-vision-port/commit/590760380a34a65cea0b259cebd00a9c83c72d15
